#include "htmlreportgenerator.h"

HtmlReportGenerator::HtmlReportGenerator()
{
    model = nullptr;
}

HtmlReportGenerator::~HtmlReportGenerator()
{

}

void HtmlReportGenerator::setModel(RequirementsModel *model)
{
    this->model = model;
}

void HtmlReportGenerator::generate(const QString &filePath)
{
    QFile file(filePath);
    if(file.open(QFile::WriteOnly)){
        file.write("File Generated by HtmlReportGenerator.");
    }
    file.close();
}

